import {
  HomeIcon,
  HashIcon,
  BlockContentIcon,
  SchemaIcon,
  EnvelopeIcon,
  VideoIcon,
  BlockElementIcon,
  ComponentIcon,
  UploadIcon,
  CogIcon,
  ComposeIcon,
  StackCompactIcon,
  CommentIcon,
} from '@sanity/icons';

export const adminStructure = (S) => 
  S.list()
    .title('WMPCA Admin')
    .items([
      S.listItem()
        .title('Front Page and Menu')
        .icon(HomeIcon)
        .child(
          S.document()
          .title('Front Page and Menu')
          .schemaType('main')
          .id('global-main')
        ),
      S.listItem()
        .title('Footer')
        .icon(HashIcon)
        .child(
          S.document()
          .schemaType('footer')
          .id('global-footer')
        ),
      S.listItem()
        .title('Blog Posts')
        .icon(BlockContentIcon)
        .child(
          S.documentTypeList('blog_post')
        ),
      S.listItem()
        .title('Pages')
        .icon(SchemaIcon)
        .child(
          S.documentTypeList('page')
        ),
      S.listItem()
        .title('Newsletter')
        .icon(EnvelopeIcon)
        .child(
          S.documentTypeList('newsletter')
        ),
      S.listItem()
        .title('Video')
        .icon(VideoIcon)
        .child(
          S.documentTypeList('video')
        ),
      S.listItem()
        .title('Body Content')
        .icon(BlockElementIcon)
        .child(
          S.list()
            .title('Body Content')
            .items([
              S.listItem()
                .title('Forms')
                .child(
                  S.documentTypeList('form')
                )
            ])
        ),
      S.listItem()
        .title('Categories')
        .icon(ComponentIcon)
        .child(
          S.list()
            .title('Categories')
            .items([
              S.listItem()
                .title('Author')
                .icon(BlockContentIcon)
                .child(
                  S.documentTypeList('author')
                ),
              S.listItem()
                .title('Category')
                .icon(ComponentIcon)
                .child(
                  S.documentTypeList('category')
                ),
              S.listItem()
                .title('Speaker')
                .icon(CommentIcon)
                .child(
                  S.documentTypeList('speaker')
                ),
              S.listItem()
                .title('Series')
                .icon(StackCompactIcon)
                .child(
                  S.documentTypeList('videoseries')
                )
            ])
        ),
      S.listItem()
        .title('Form Submissions')
        .icon(ComposeIcon)
        .child(
          S.documentTypeList('submission')
        ),
      S.listItem()
        .title('File Uploads')
        .icon(UploadIcon)
        .child(
          S.documentTypeList('fileUpload')
        ),
      S.divider(),
      S.listItem()
        .title('Config')
        .icon(CogIcon)
        .child(
          S.document()
          .schemaType('config')
          .id('global-config')
        )
    ]);